jqassistant.store.provider=neo4jv5
jqassistant.store.uri=bolt://localhost:7687
jqassistant.store.username=neo4j
jqassistant.store.password=neo4j12345
jqassistant.scan.includes=/Users/oliverwidder/dev/ofbiz/build/classes/java/main
